version: "3"

volumes:
  local_template_postgres_data: {}
  local_postgres_data_backups: {}

services:
  nextjs:
    build:
      context: .
      dockerfile: ./lib/serverless/compose/nextjs/dev/Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  postgres:
    build:
      context: .
      dockerfile: ./lib/serverless/compose/postgres/Dockerfile
    image: local_postgres
    container_name: local_postgres
    volumes:
      - local_template_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: local_redis
